name: Example workflow using Snyk
on: ['push', 'pull_request']
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'SETUP: Java version'
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
